name: Delete Completed Todoist Tasks

on:
  schedule: 
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  delete_completed_tasks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Delete completed tasks in Todoist
        env:
          TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
        run: |
          
         
          curl -X POST "https://api.todoist.com/sync/v9/completed/get" \
            -H "Authorization: Bearer $TODOIST_API_TOKEN" \
            -d 'filter="completed_since:today"' > completed_tasks.json

       
          cat completed_tasks.json | jq -r '.items[].id' | while read task_id; do
            curl -X POST "https://api.todoist.com/sync/v8/completed/delete" \
              -H "Authorization: Bearer $TODOIST_API_TOKEN" \
              -d "task_id=$task_id"
          done
