name: Delete Completed Todoist Tasks

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  delete_completed_tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Delete completed tasks in Todoist
      env:
        TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
      run: |
        # jq 설치 (필요시, jq가 미리 설치된 Docker 이미지를 사용할 수 있음)
        sudo apt-get install -y jq

        # Todoist API에서 완료된 작업을 가져옵니다
        response=$(curl -s \
          -X GET \
          -H "Authorization: Bearer $TODOIST_API_KEY" \
          "https://api.todoist.com/sync/v8/completed/get")

        # 응답이 비어있거나 형식이 잘못되었으면 처리
        if [[ -z "$response" || "$response" == "{}" ]]; then
          echo "완료된 작업이 없습니다."
          exit 0
        fi

        # 응답에 오류가 포함되어 있는지 확인
        if [[ "$response" == *"error"* ]]; then
          echo "오류 발생: $response"
          exit 1
        fi

        # 완료된 작업 ID를 추출하고 삭제
        echo "$response" | jq -r '.items[] | .id' | while read task_id; do
          echo "삭제 중인 작업 ID: $task_id"
          curl -s \
            -X DELETE \
            -H "Authorization: Bearer $TODOIST_API_KEY" \
            "https://api.todoist.com/rest/v2/tasks/$task_id"
        done
